# Generated by Django 5.2.3 on 2025-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatinghour',
            name='day',
        ),
        migrations.AddField(
            model_name='operatinghour',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
