# Generated by Django 5.2.3 on 2025-07-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_remove_operatinghour_day_operatinghour_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(default='tourist_spots/default.jpg', upload_to='tourist_spots/'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
