# Generated by Django 5.2.3 on 2025-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_savedspot_visitedspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='embed_link',
            field=models.TextField(blank=True, help_text='Google Maps embed link'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='website_link',
            field=models.URLField(blank=True, help_text='Social media or website link'),
        ),
    ]
