# Generated by Django 5.2.3 on 2025-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_touristspot_embed_link_touristspot_website_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismReportedSpotAlbay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tourism Reported Spot',
                'verbose_name_plural': 'Tourism Reported Spots',
                'db_table': 'tourism_reported_spots_albay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportedSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reported_spots/')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
