# Generated by Django 5.2.3 on 2025-08-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_tourismreportedspotalbay_reportedspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='embed_link',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed link'),
        ),
    ]
