# Generated by Django 5.2.3 on 2025-09-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_remove_touristspot_embed_link_touristspot_map_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='website_link',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='name_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
