# Generated by Django 5.2.3 on 2025-09-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_remove_touristspot_website_link_touristspot_name_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='tourism.category'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='tourism.location'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='tourism_touristspot_category',
        ),
        migrations.AlterModelTable(
            name='location',
            table='tourism_location',
        ),
        migrations.AlterModelTable(
            name='tourismreportedspotalbay',
            table='tourism_touristspot',
        ),
        migrations.AlterModelTable(
            name='touristspot',
            table='tourism_touristspot',
        ),
    ]
