# Generated by Django 5.2.3 on 2025-07-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/objects/')),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('offset_z', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='ar.arscene')),
            ],
        ),
    ]
