# Generated by Django 5.2.3 on 2025-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_arobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arscene',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/models/'),
        ),
    ]
